Repository yonghoya/AI_Security_Network_Project, pull requests merged in 2023-09, with the labels that each got.

#10 output page 수정
  templates/main/output.html
Labels: fix

#11 method 변경 및 폼 크기 수정
  main/views.py
  templates/main/input.html
Labels: fix

#19 Add exception handling code
  checkurl/views.py
Labels: bug, fix

#20 url 정보를 저장하는 모델 만들기
  checkurl/migrations/0001_initial.py
  checkurl/models.py
  db.sqlite3
Labels: feature

#21 Db model use, AI function add
  checkurl/migrations/0001_initial.py
  checkurl/models.py
  checkurl/views.py
  config/settings.py
  db.sqlite3
Labels: feature

#24 멀티프로세싱 루틴 추가
  checkurl/__pycache__/__init__.cpython-311.pyc
  checkurl/__pycache__/admin.cpython-311.pyc
  checkurl/__pycache__/apps.cpython-311.pyc
  checkurl/__pycache__/models.cpython-311.pyc
  checkurl/__pycache__/multi.cpython-311.pyc
  checkurl/__pycache__/tests.cpython-311.pyc
  checkurl/__pycache__/views.cpython-311.pyc
  checkurl/migrations/0001_initial.py
  checkurl/migrations/__pycache__/0001_initial.cpython-311.pyc
  checkurl/migrations/__pycache__/0002_url_judge.cpython-311.pyc
  checkurl/migrations/__pycache__/__init__.cpython-311.pyc
  checkurl/models.py
  checkurl/multi.py
  checkurl/tests.py
  checkurl/top500Domains.csv
  checkurl/views.py
  config/wsgi.py
  db.sqlite3
Labels: fix, feature

#25 include 함수로 url 매핑
  checkurl/urls.py
  config/urls.py
Labels: fix

#26 Output page data
  checkurl/views.py
  config/settings.py
  templates/checkurl/output.html
Labels: fix, feature

#27 크롬 플러그인 통신용 api 구현
  checkurl/urls.py
  checkurl/views.py
Labels: feature

#28 input page 디자인 수정
  templates/checkurl/input.html
Labels: fix
