Repository yonghoya/AI_Security_Network_Project, pull requests merged in 2023-08, with the labels that each got.

#5 Output page 구현
  .idea/dbnavigator.xml
  config/settings.py
  main/urls.py
  main/views.py
  static/phishing_box.png
  templates/main/output.html
Labels: feature

#6 Input page
  templates/main/input.html
  templates/main/output.html
Labels: fix, feature

#8 Revert "Ai model"
  ai_model/Network Project AI.ipynb
  ai_model/model_bert_logreg.pkl
  ai_model/model_example.py
  ai_model/tempfile
  ai_model/중간보고회 시연용.ipynb
Labels: fix
